<?php
/* $Id$ */

/**
 * @file
 * Uses the reCAPTCHA web service to improve the CAPTCHA system.
 */

/**
 * Display help and module information.
 *
 * @param $path
 *   The path of the section of the site we're displaying help for.
 * @return
 *   Help text for section.
 */
function recaptcha_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/modules#name':
      $output .= t('reCAPTCHA');
      break;
    case 'admin/modules#description':
    case 'admin/user/captcha/recaptcha':
      $output .= t('Uses the <a href="@url" target="_blank">reCAPTCHA</a> web service to improve the CAPTCHA system and protect email addresses.', array('@url' => url('http://www.recaptcha.net')));
      break;
    case 'admin/help#recaptcha':
      $output .= '<p>'.
        t('Uses the reCAPTCHA web service to improve the CAPTCHA module and protect email addresses. For more information on what reCAPTCHA is, visit <a href="@url" target="_blank">the official website</a>.', array('@url' => url('http://www.recaptcha.net'))) .
        '</p><h3>'.
        t('Configuration') .
        '</h3><p>'.
        t('The settings associated with reCAPTCHA can be found in the <a href="@recaptchatab">reCAPTCHA tab</a>, in the <a href="@captchasettings">CAPTCHA settings</a>. You must set your public and private reCAPTCHA keys in order to use the module. Once the public and private keys are set, visit the <a href="@captchasettings">CAPTCHA settings</a>, where you can choose where reCAPTCHA should be displayed.', array('@recaptchatab' => url('admin/user/captcha/recaptcha'), '@captchasettings' => url('admin/user/captcha'))) .
        '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_menu().
 */
function recaptcha_menu() {
  $items = array();
  $items['admin/user/captcha/recaptcha'] = array(
    'title' => 'reCAPTCHA',
    'description' => 'Administer the reCAPTCHA web service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recaptcha_admin_settings'),
    'access arguments' => array('administer recaptcha'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function recaptcha_perm() {
  return array('administer recaptcha');
}

/**
 * Form callback; administrative settings for reCaptcha.
 */
function recaptcha_admin_settings() {
  // Load the recaptcha library.
  recaptcha_load_library();

  $form = array();
  $form['recaptcha_public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Public Key'),
    '#default_value' => variable_get('recaptcha_public_key', ''),
    '#maxlength' => 40,
    '#description' => t('The public key given to you when you <a href="@url" target="_blank">registered at reCAPTCHA.net</a>.', array('@url' => url(recaptcha_get_signup_url($_SERVER['SERVER_NAME'], variable_get('site_name', ''))))),
    '#required' => TRUE,
   );
  $form['recaptcha_private_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Private Key'),
    '#default_value' => variable_get('recaptcha_private_key', ''),
    '#maxlength' => 40,
    '#description' => t('The private key given to you when you <a href="@url" target="_blank">registered at reCAPTCHA.net</a>.', array('@url' => url(recaptcha_get_signup_url($_SERVER['SERVER_NAME'], variable_get('site_name', ''))))),
    '#required' => TRUE,
  );
  $form['recaptcha_secure_connection'] = array(
    '#type' => 'checkbox',
    '#title' => t('Secure Connection'),
    '#default_value' => variable_get('recaptcha_secure_connection', FALSE),
    '#description' => t('Connect to the reCAPTCHA server using a secure connection.'),
  );
  $form['recaptcha_theme_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Theme Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['recaptcha_theme_settings']['recaptcha_theme'] = array(
    '#type' => 'select',
    '#title' => t('Theme'),
    '#description' => t('Defines which theme to use for reCAPTCHA.'),
    '#options' => array(
      'red' => t('Red'),
      'white' => t('White'),
      'blackglass' => t('Black Glass'),
      'clean' => t('Clean'),
      'custom' => t('Custom'),
    ),
    '#default_value' => variable_get('recaptcha_theme', 'red'),
    '#required' => TRUE,
  );
  $form['recaptcha_theme_settings']['recaptcha_tabindex'] = array(
    '#type' => 'textfield',
    '#title' => t('Tab Index'),
    '#description' => t('Sets a <a href="@tabindex" target="_blank">tabindex</a> for the reCAPTCHA text box. If other elements in the form use a tabindex, this should be set so that navigation is easier for the user.', array('@tabindex' => 'http://www.w3.org/TR/html4/interact/forms.html#adef-tabindex')),
    '#default_value' => variable_get('recaptcha_tabindex', ''),
    '#size' => 4,
  );

  return system_settings_form($form);
}

/**
 * Validation function for recaptcha_admin_settings().
 *
 * @see recaptcha_admin_settings()
 */
function recaptcha_admin_settings_validate($form, &$form_state) {
  $tabindex = $form_state['values']['recaptcha_tabindex'];
  if (!empty($tabindex) && !is_numeric($tabindex)) {
    form_set_error('recaptcha_tabindex', t('The Tab Index must be an integer.'));
  }
}

/**
 * Load the recaptcha library.
 */
function recaptcha_load_library() {
  $path = drupal_get_path('module', 'recaptcha');
  require_once($path . '/recaptcha.inc');
  if (!include_once($path . '/recaptcha/recaptchalib.php')) {
    _recaptcha_library_not_found();
  }
}

/**
 * Implementation of hook_captcha().
 */
function recaptcha_captcha() {
  $args = func_get_args();
  $op = array_shift($args); 
  switch ($op) {
    case 'list':
      return array('reCAPTCHA');

    case 'generate':
      $captcha_type = array_shift($args);
      $result = array();
      if ($captcha_type == 'reCAPTCHA') {
        // Load the recaptcha library.
        recaptcha_load_library();

        static $_recaptcha_jsadded = FALSE;

        // Check if reCAPTCHA is available and show Math if not.
        $connect = @fsockopen(RECAPTCHA_VERIFY_SERVER, 80);
        if (!$connect) {
          return captcha_captcha('generate', 'Math', $args);
        }
        fclose($connect);

        // Retrieve configuration variables from database.
        $recaptcha_secure_connection = variable_get('recaptcha_secure_connection', FALSE);
        $recaptcha_theme = variable_get('recaptcha_theme', 'red');
        $recaptcha_tabindex = variable_get('recaptcha_tabindex', NULL);
        $recaptcha_public_key = variable_get('recaptcha_public_key', '');
        $recaptcha_form_value = NULL;

        // Construct the Javascript, but only display it once.
        if ($_recaptcha_jsadded == FALSE) {
          $_recaptcha_jsadded = TRUE;
          $recaptcha_options = array(
            'theme' => $recaptcha_theme,
          );

          // Localization support.
          global $language;
          if (isset($language->language)) {
            // reCAPTCHA uses two-character language codes, so 'pt-br' must be
            // passed as 'pt' (cf. http://wiki.recaptcha.net/index.php/I18n).
            $recaptcha_options['lang'] = substr($language->language, 0, 2);
          }

          // Add support to display the custom theme.
          if ($recaptcha_theme == 'custom') {
            $recaptcha_options['custom_theme_widget'] = 'recaptcha_custom_theme_widget';
            $recaptcha_form_value = theme('recaptcha_custom_widget');
          }

          // Set the default tab index.
          if (!empty($recaptcha_tabindex)) {
            $recaptcha_options['tabindex'] = $recaptcha_tabindex;
          }
          drupal_add_js('var RecaptchaOptions = '. drupal_to_js($recaptcha_options) .';', 'inline');
        }

        // Create the form. Captcha requires TRUE to be returned in solution.
        $result['solution'] = TRUE;
        $result['form']['captcha_response'] = array(
          '#type' => 'item',
          '#description' => recaptcha_get_html($recaptcha_public_key, NULL, $recaptcha_secure_connection),
          '#required' => TRUE,
          '#value' => $recaptcha_form_value ? '<div id="recaptcha_custom_theme_widget">'. $recaptcha_form_value .'</div>' : NULL,
          // Make sure this 'item' form element is handled as an input element 
          // so that a '#process' callback can be attached.
          '#input' => TRUE, 
          '#process' => array('recaptcha_process'), 
        );
      }
      return $result;
  }
}

/**
 * Implementation of hook_theme().
 */ 
function recaptcha_theme() {
  return array(
    'recaptcha_custom_widget' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * Theme function: creates the custom themed recaptcha widget.
 *
 * @ingroup themeable
 */
function theme_recaptcha_custom_widget() {
  $recaptcha_only_if_incorrect_sol = t('Incorrect please try again');
  $recaptcha_only_if_image_enter = t('Enter the words above:');
  $recaptcha_only_if_audio_enter = t('Enter the numbers you hear:');
  $recaptcha_get_another_captcha = t('Get another CAPTCHA');
  $recaptcha_only_if_image = t('Get an audio CAPTCHA');
  $recaptcha_only_if_audio = t('Get an image CAPTCHA');
  $help = t('Help');
  return <<<EOT
    <div id="recaptcha_image"></div>
    <div class="recaptcha_only_if_incorrect_sol" style="color:red">$recaptcha_only_if_incorrect_sol</div>
    <span class="recaptcha_only_if_image">$recaptcha_only_if_image_enter</span>
    <span class="recaptcha_only_if_audio">$recaptcha_only_if_audio_enter</span>
    <input type="text" id="recaptcha_response_field" name="recaptcha_response_field" />
    <div class="recaptcha_get_another_captcha"><a href="javascript:Recaptcha.reload()">$recaptcha_get_another_captcha</a></div>
    <div class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')">$recaptcha_only_if_image</a></div>
    <div class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')">$recaptcha_only_if_audio</a></div>
    <div class="recaptcha_help"><a href="javascript:Recaptcha.showhelp()">$help</a></div>
EOT;
}

/**
 * Process function: fetch the validation result from reCAPTCHA server and pass it to the Drupal CAPTCHA API.
 */
function recaptcha_process($element, $edit, &$form_state, $complete_form) {
  if (isset($_POST['recaptcha_challenge_field']) && isset($_POST['recaptcha_response_field'])) {
    $resp = recaptcha_check_answer(
      variable_get('recaptcha_private_key', ''),
      $_SERVER['REMOTE_ADDR'],
      $_POST['recaptcha_challenge_field'],
      $_POST['recaptcha_response_field']
    );
    if ($resp->is_valid) {
      $element['#value'] = TRUE;
    }
    else {
      form_set_error('captcha_response', t('The reCAPTCHA code you entered was incorrect.'));
      $element['#value'] = FALSE;
    }
  }
  return $element;
}
